name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    container:
        image: antkiller996/rust-tugraph:latest
        env:
          LGRAPH_CXX_COMPILER: /usr/local/bin/g++
          LGRAPH_C_COMPILER: /usr/local/bin/gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.68.0
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}