name: CI

on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: antkiller996/rust-tugraph:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cargo fmt --all --check
  check-doc:
    runs-on: ubuntu-latest
    container:
      image: antkiller996/rust-tugraph:latest
      env:
        LGRAPH_CXX_COMPILER: /usr/local/bin/g++
        LGRAPH_C_COMPILER: /usr/local/bin/gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cargo doc --no-deps --all-features --all
  clippy:
    runs-on: ubuntu-latest
    container:
      image: antkiller996/rust-tugraph:latest
      env:
        LGRAPH_CXX_COMPILER: /usr/local/bin/g++
        LGRAPH_C_COMPILER: /usr/local/bin/gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cargo clippy --all --all-features -- -D warnings
  test:
    runs-on: ubuntu-latest
    container:
      image: antkiller996/rust-tugraph:latest
      env:
        LGRAPH_CXX_COMPILER: /usr/local/bin/g++
        LGRAPH_C_COMPILER: /usr/local/bin/gcc
    needs: [fmt, check-doc, clippy]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./scripts/test_all.sh

